version: 2
build:
  os: ubuntu-lts-latest
  commands:
    - sphinx-build -v -b html . _build/html  # Command to run Sphinx and build HTML docs
python:
  install:
    - pip install -U -r requirements.txt  # Upgrade dependencies and install from requirements.txt
