version: 2
build:
  os: ubuntu-lts-latest
  commands:
    - sphinx-build -b html . _build/html  # Command to run Sphinx and build HTML docs
python:
  install:
    - requirements: requirements.txt  # Install dependencies from requirements.txt
