version: 2
build:
  image: latest
  os: ubuntu
python:
  install:
    - requirements: requirements.txt  # Points to the requirements file
  pip_extra_index_url: https://581351078906.d.codeartifact.us-east-1.amazonaws.com/pypi/python/simple/  # Your CodeArtifact URL
